export enum TestID {
  TEST = 'test',
  APP = 'app',
  CUSTOM404 = 'custom404',
  CUSTOM500 = 'custom500',
  NAVBAR = 'navbar',
  PROFILE_BUTTON = 'profile-button',
  BLOG_ITEM = 'blog-item',
  SKILL_ITEM = 'skill-item',
  PROJECT_ITEM = 'project-item',
  TECHNOLOGY_BADGE = 'technology-badge',
  PAGING_FIRST_BUTTON = 'paging-first-button',
  PAGING_PREVIOUS_BUTTON = 'paging-previous-button',
  PAGING_NEXT_BUTTON = 'paging-next-button',
  PAGING_LAST_BUTTON = 'paging-last-button',
}
