query getAll {
  blogs {
    items {
      ...Blog
      tags {
        blogId
        technology {
          id
        }
      }
    }
    totalCount
  }
  projects {
    id
    title
    description
    isFavorite
    position
    githubLink
    qiitaLink
    appLink
    createdAt
    updatedAt
    tags {
      projectId
      technology {
        id
      }
    }
  }
  technologies {
    id
    name
    logoUrl
    tagColor
    createdAt
    updatedAt
  }
  techStacks {
    id
    proficiency
    technologyId
    createdAt
    updatedAt
  }
}
