query getBlogs {
  blogs {
    id
    title
    url
    kind
    publishedAt
    createdAt
    updatedAt
  }
}
query getBlog($id: Uint!) {
  blog(id: $id) {
    id
    title
    url
    kind
    publishedAt
    createdAt
    updatedAt
  }
}
query getBlogWithTags($id: Uint!) {
  blog(id: $id) {
    id
    title
    url
    kind
    publishedAt
    createdAt
    updatedAt
    tags {
      id
      name
      logoUrl
      tagColor
      createdAt
      updatedAt
    }
  }
}
mutation createBlog($input: BlogInput!) {
  createBlog(input: $input) {
    id
    title
    url
    kind
    publishedAt
    createdAt
    updatedAt
  }
}
mutation updateBlogWithTags($id: Uint!, $input: BlogInput!, $tags: [Uint!]!) {
  updateBlog(id: $id, input: $input) {
    id
    title
    url
    kind
    publishedAt
    createdAt
    updatedAt
  }
  updateBlogTags(id: $id, tags: $tags) {
    id
    name
    logoUrl
    tagColor
    createdAt
    updatedAt
  }
}
mutation deleteBlog($id: Uint!) {
  deleteBlog(id: $id) {
    id
    title
    url
    kind
    publishedAt
    createdAt
    updatedAt
  }
}
mutation updateBlogTags($id: Uint!, $tags: [Uint!]!) {
  updateBlogTags(id: $id, tags: $tags) {
    id
    name
    logoUrl
    tagColor
    createdAt
    updatedAt
  }
}
