fragment Blog on Blog {
  id
  title
  url
  kind
  publishedAt
  createdAt
  updatedAt
}
query getBlogs($opt: ListOpt) {
  blogs(opt: $opt) {
    items {
      ...Blog
    }
    totalCount
  }
}
query getBlog($id: Uint!) {
  blog(id: $id) {
    ...Blog
  }
}
query getBlogWithTags($id: Uint!) {
  blog(id: $id) {
    ...Blog
    tags {
      blogId
      technology {
        id
        name
        logoUrl
        tagColor
        createdAt
        updatedAt
      }
    }
  }
}
mutation createBlog($input: BlogInput!) {
  createBlog(input: $input) {
    ...Blog
  }
}
mutation updateBlogWithTags($id: Uint!, $input: BlogInput!, $tags: [Uint!]!) {
  updateBlog(id: $id, input: $input) {
    ...Blog
  }
  updateBlogTags(id: $id, tags: $tags) {
    blogId
    technology {
      id
      name
      logoUrl
      tagColor
      createdAt
      updatedAt
    }
  }
}
mutation deleteBlog($id: Uint!) {
  deleteBlog(id: $id) {
    ...Blog
  }
}
mutation updateBlogTags($id: Uint!, $tags: [Uint!]!) {
  updateBlogTags(id: $id, tags: $tags) {
    blogId
    technology {
      id
      name
      logoUrl
      tagColor
      createdAt
      updatedAt
    }
  }
}
