fragment Blog on Blog {
  id
  title
  url
  kind
  publishedAt
  createdAt
  updatedAt
}
fragment BlogTag on BlogTag {
  blogId
  technology {
    ...TechnologyFragment
  }
}
query getBlogs($opt: ListOpt) {
  blogs(opt: $opt) {
    items {
      ...Blog
    }
    totalCount
  }
}
query getBlog($id: Uint!) {
  blog(id: $id) {
    ...Blog
  }
}
query getBlogWithTags($id: Uint!) {
  blog(id: $id) {
    ...Blog
    tags {
      ...BlogTag
    }
  }
}
mutation createBlog($input: BlogInput!) {
  createBlog(input: $input) {
    ...Blog
  }
}
mutation updateBlogWithTags($id: Uint!, $input: BlogInput!, $tags: [Uint!]!) {
  updateBlog(id: $id, input: $input) {
    ...Blog
  }
  updateBlogTags(id: $id, tags: $tags) {
    ...BlogTag
  }
}
mutation deleteBlog($id: Uint!) {
  deleteBlog(id: $id) {
    ...Blog
  }
}
mutation updateBlogTags($id: Uint!, $tags: [Uint!]!) {
  updateBlogTags(id: $id, tags: $tags) {
    ...BlogTag
  }
}
