query getProjects {
  projects {
    id
    title
    description
    isFavorite
    position
    appLink
    githubLink
    qiitaLink
    createdAt
    updatedAt
  }
}
query getProject($id: String!) {
  project(id: $id) {
    id
    title
    description
    isFavorite
    position
    appLink
    githubLink
    qiitaLink
    createdAt
    updatedAt
  }
}
query getProjectWithTags($id: String!) {
  project(id: $id) {
    id
    title
    description
    isFavorite
    position
    appLink
    githubLink
    qiitaLink
    createdAt
    updatedAt
    tags {
      id
      name
      logoUrl
      tagColor
      createdAt
      updatedAt
    }
  }
}
mutation createProject($input: ProjectInput!) {
  createProject(input: $input) {
    id
    title
    description
    isFavorite
    position
    appLink
    githubLink
    qiitaLink
    createdAt
    updatedAt
  }
}
mutation updateProject($input: ProjectInput!) {
  updateProject(input: $input) {
    id
    title
    description
    isFavorite
    position
    appLink
    githubLink
    qiitaLink
    createdAt
    updatedAt
  }
}
mutation updateProjectWithTags(
  $id: String!
  $input: ProjectInput!
  $tags: [Uint!]!
) {
  updateProject(input: $input) {
    id
    title
    description
    isFavorite
    position
    appLink
    githubLink
    qiitaLink
    createdAt
    updatedAt
  }
  updateProjectTags(id: $id, tags: $tags) {
    id
    name
    logoUrl
    tagColor
    createdAt
    updatedAt
  }
}
mutation deleteProject($id: String!) {
  deleteProject(id: $id) {
    id
    title
    description
    isFavorite
    position
    appLink
    githubLink
    qiitaLink
    createdAt
    updatedAt
  }
}
mutation updateProjectTags($id: String!, $tags: [Uint!]!) {
  updateProjectTags(id: $id, tags: $tags) {
    id
    name
    logoUrl
    tagColor
    createdAt
    updatedAt
  }
}
mutation updateProjectOrder($input: UpdateProjectOrderInput!) {
  updateProjectOrder(input: $input) {
    id
    title
    description
    isFavorite
    position
    appLink
    githubLink
    qiitaLink
    createdAt
    updatedAt
  }
}
