query getTechStacks {
  techStacks {
    id
    technologyId
    technology {
      id
      name
      logoUrl
    }
    proficiency
    createdAt
    updatedAt
  }
}

query getTechStack($id: Uint!) {
  techStack(id: $id) {
    id
    technologyId
    technology {
      id
      name
      logoUrl
    }
    proficiency
    createdAt
    updatedAt
  }
}

mutation createTechStack($input: TechStackInput!) {
  createTechStack(input: $input) {
    id
    technologyId
    proficiency
    createdAt
    updatedAt
  }
}

mutation updateTechStack($id: Uint!, $input: TechStackInput!) {
  updateTechStack(id: $id, input: $input) {
    id
    technologyId
    proficiency
    createdAt
    updatedAt
  }
}

mutation deleteTechStack($id: Uint!) {
  deleteTechStack(id: $id) {
    id
    technologyId
    proficiency
    createdAt
    updatedAt
  }
}
