fragment TechStack on TechStack {
  id
  technologyId
  proficiency
  createdAt
  updatedAt
}
query getTechStacks {
  techStacks {
    ...TechStack
    technology {
      id
      name
      logoUrl
    }
  }
}

query getTechStack($id: Uint!) {
  techStack(id: $id) {
    ...TechStack
    technology {
      id
      name
      logoUrl
    }
  }
}

mutation createTechStack($input: TechStackInput!) {
  createTechStack(input: $input) {
    ...TechStack
  }
}

mutation updateTechStack($id: Uint!, $input: TechStackInput!) {
  updateTechStack(id: $id, input: $input) {
    ...TechStack
  }
}

mutation deleteTechStack($id: Uint!) {
  deleteTechStack(id: $id) {
    ...TechStack
  }
}
