fragment TechnologyFragment on Technology {
  id
  name
  logoUrl
  tagColor
  createdAt
  updatedAt
}
query getTechnologies {
  technologies {
    ...TechnologyFragment
  }
}
query getTechnology($id: Uint!) {
  technology(id: $id) {
    ...TechnologyFragment
  }
}
mutation createTechnology($input: TechnologyInput!) {
  createTechnology(input: $input) {
    ...TechnologyFragment
  }
}
mutation updateTechnology($id: Uint!, $input: TechnologyInput!) {
  updateTechnology(id: $id, input: $input) {
    ...TechnologyFragment
  }
}
mutation deleteTechnology($id: Uint!) {
  deleteTechnology(id: $id) {
    ...TechnologyFragment
  }
}
