query getTechnologies {
  technologies {
    id
    name
    logoUrl
    tagColor
    createdAt
    updatedAt
  }
}
query getTechnology($id: Uint!) {
  technology(id: $id) {
    id
    name
    logoUrl
    tagColor
    createdAt
    updatedAt
  }
}
mutation createTechnology($input: TechnologyInput!) {
  createTechnology(input: $input) {
    id
    name
    logoUrl
    tagColor
    createdAt
    updatedAt
  }
}
mutation updateTechnology($id: Uint!, $input: TechnologyInput!) {
  updateTechnology(id: $id, input: $input) {
    id
    name
    logoUrl
    tagColor
    createdAt
    updatedAt
  }
}
mutation deleteTechnology($id: Uint!) {
  deleteTechnology(id: $id) {
    id
    name
    logoUrl
    tagColor
    createdAt
    updatedAt
  }
}
