// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package domain

type BlogInput struct {
	Title  string `json:"title"`
	URL    string `json:"url"`
	Kind   int    `json:"kind"`
	TagIds []uint `json:"tagIds"`
}

type Mutation struct {
}

type ProjectInput struct {
	ID          string `json:"id"`
	Title       string `json:"title"`
	Description string `json:"description"`
	IsFavorite  bool   `json:"isFavorite"`
}

type Query struct {
}

type TechnologyInput struct {
	Name     string  `json:"name"`
	LogoURL  *string `json:"logoUrl,omitempty"`
	TagColor string  `json:"tagColor"`
}
