type Blog {
  id: Uint!
  title: String!
  url: String!
  kind: Int!
  tags: [Technology!]!
  createdAt: Time!
  updatedAt: Time!
}
input BlogInput {
  title: String!
  url: String!
  kind: Int!
  tagIds: [Uint!]!
}

extend type Query {
  blogs: [Blog!]!
  blog(id: Uint!): Blog!
}
extend type Mutation {
  createBlog(input: BlogInput!): Blog!
  updateBlog(id: Uint!, input: BlogInput!): Blog!
  deleteBlog(id: Uint!): Blog!
}
