type Project {
  id: String!
  title: String!
  description: String!
  isFavorite: Boolean!
  githubLink: String
  qiitaLink: String
  appLink: String
  tags: [Technology!]!
  createdAt: Time!
  updatedAt: Time!
}
input ProjectInput {
  id: String!
  title: String!
  description: String!
  isFavorite: Boolean!
  githubLink: String
  qiitaLink: String
  appLink: String
}

extend type Query {
  projects: [Project!]!
  project(id: String!): Project!
}
extend type Mutation {
  createProject(input: ProjectInput!): Project!
  updateProject(input: ProjectInput!): Project!
  deleteProject(id: String!): Project!
  updateProjectTags(id: String!, tags: [Uint!]!): [Technology!]!
}
