// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"fmt"
	"io"
	"strconv"
	"time"
)

type Blog struct {
	ID        uint      `json:"id"`
	Title     string    `json:"title"`
	URL       string    `json:"url"`
	Kind      BlogKind  `json:"kind"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

type Mutation struct {
}

type Project struct {
	ID          string    `json:"id"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	IsFavorite  bool      `json:"isFavorite"`
	CreatedAt   time.Time `json:"createdAt"`
	UpdatedAt   time.Time `json:"updatedAt"`
}

type Query struct {
}

type BlogKind string

const (
	BlogKindQiita BlogKind = "QIITA"
)

var AllBlogKind = []BlogKind{
	BlogKindQiita,
}

func (e BlogKind) IsValid() bool {
	switch e {
	case BlogKindQiita:
		return true
	}
	return false
}

func (e BlogKind) String() string {
	return string(e)
}

func (e *BlogKind) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = BlogKind(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid BlogKind", str)
	}
	return nil
}

func (e BlogKind) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
