version: '3'

services:
  app:
    container_name: portfolio
    image: portfolio
    build:
      context: .
      dockerfile: Dockerfile
    restart: always

  nginx:
    container_name: portfolio-nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 54000:80
    depends_on:
      - app
