fragment Blog on Blog {
  id
  title
  url
  kind
  publishedAt
  createdAt
  updatedAt
}
fragment Project on Project {
  id
  title
  description
  isFavorite
  position
  appLink
  githubLink
  qiitaLink
  createdAt
  updatedAt
}
fragment Technology on Technology {
  id
  name
  logoUrl
  tagColor
  createdAt
  updatedAt
}
fragment BlogTag on BlogTag {
  blogId
  technology {
    ...Technology
  }
}
fragment ProjectTag on ProjectTag {
  projectId
  technology {
    ...Technology
  }
}
query fetchAllData {
  blogs {
    items {
      ...Blog
      tags {
        ...BlogTag
      }
    }
  }
  projects {
    ...Project
    tags {
      ...ProjectTag
    }
  }
  techStacks {
    id
    technologyId
    technology {
      ...Technology
    }
    proficiency
    createdAt
    updatedAt
  }
}
query fetchBlogs($opt: ListOpt) {
  blogs(opt: $opt) {
    items {
      ...Blog
      tags {
        ...BlogTag
      }
    }
    totalCount
  }
}
query fetchProjects {
  projects {
    ...Project
    tags {
      ...ProjectTag
    }
  }
}
query fetchProject($id: String!) {
  project(id: $id) {
    ...Project
    tags {
      ...ProjectTag
    }
  }
}
query fetchTechStacks {
  techStacks {
    id
    technologyId
    technology {
      ...Technology
    }
    proficiency
    createdAt
    updatedAt
  }
}
query fetchTechnology($id: Uint!) {
  projects {
    ...Project
    tags {
      ...ProjectTag
    }
  }
  blogs {
    items {
      ...Blog
      tags {
        ...BlogTag
      }
    }
  }
  technology(id: $id) {
    ...Technology
  }
}
