query getBlogs {
  blogs {
    id
    title
    url
    kind
    tags {
      id
      name
      tagColor
    }
  }
}
query getProjects {
  projects {
    id
    title
    description
    isFavorite
    githubLink
    qiitaLink
    appLink
    tags {
      id
      name
      tagColor
    }
  }
}

query getTechStacks {
  techStacks {
    id
    technology {
      id
      name
      tagColor
      logoUrl
    }
    proficiency
  }
}
