query getBlogs {
  blogs {
    id
    title
    url
    kind
    createdAt
    updatedAt
  }
}
query getBlog($id: Uint!) {
  blog(id: $id) {
    id
    title
    url
    kind
    createdAt
    updatedAt
  }
}
