package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.42

import (
	"admin-backend/graph"
	"admin-backend/graph/model"
	"context"
	"fmt"
)

func (r *mutationResolver) CreateBlog(ctx context.Context, title string, url string, kind model.BlogKind) (*model.Blog, error) {
	panic(fmt.Errorf("not implemented: CreateBlog - createBlog"))
}

func (r *mutationResolver) UpdateBlog(ctx context.Context, id uint, title string, url string, kind model.BlogKind) (*model.Blog, error) {
	panic(fmt.Errorf("not implemented: UpdateBlog - updateBlog"))
}

func (r *mutationResolver) DeleteBlog(ctx context.Context, id uint) (*model.Blog, error) {
	panic(fmt.Errorf("not implemented: DeleteBlog - deleteBlog"))
}

func (r *queryResolver) Blogs(ctx context.Context) ([]*model.Blog, error) {
	panic(fmt.Errorf("not implemented: Blogs - blogs"))
}

func (r *queryResolver) Blog(ctx context.Context) (*model.Blog, error) {
	panic(fmt.Errorf("not implemented: Blog - blog"))
}

func (r *Resolver) Mutation() graph.MutationResolver { return &mutationResolver{r} }

func (r *Resolver) Query() graph.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
