type Blog {
  id: Uint!
  title: String!
  url: String!
  kind: Int!
  tags: [BlogTag!]!
  publishedAt: Time!
  createdAt: Time!
  updatedAt: Time!
}
type BlogTag {
  blogId: Uint!
  id: Uint!
  name: String!
  logoUrl: String
  tagColor: String!
  createdAt: Time!
  updatedAt: Time!
}
input BlogInput {
  title: String!
  url: String!
  kind: Int!
  publishedAt: Time!
}

extend type Query {
  blogs: [Blog!]!
  blog(id: Uint!): Blog!
}
extend type Mutation {
  createBlog(input: BlogInput!): Blog!
  updateBlog(id: Uint!, input: BlogInput!): Blog!
  deleteBlog(id: Uint!): Blog!
  updateBlogTags(id: Uint!, tags: [Uint!]!): [BlogTag]!
}
