type Blog {
  id: Uint!
  title: String!
  url: String!
  kind: Int!
  tags: [BlogTag!]!
  publishedAt: Time!
  createdAt: Time!
  updatedAt: Time!
}
type BlogTag {
  blogId: Uint!
  technology: Technology!
}
type BlogConnection {
  items: [Blog!]!
  totalCount: Int64!
}
input BlogInput {
  title: String!
  url: String!
  kind: Int!
  publishedAt: Time!
}

extend type Query {
  blogs(opt: ListOpt): BlogConnection!
  blog(id: Uint!): Blog!
}
extend type Mutation {
  createBlog(input: BlogInput!): Blog!
  updateBlog(id: Uint!, input: BlogInput!): Blog!
  deleteBlog(id: Uint!): Blog!
  updateBlogTags(id: Uint!, tags: [Uint!]!): [BlogTag]!
}
