// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package domain

import (
	"time"
)

type BlogInput struct {
	Title       string    `json:"title"`
	URL         string    `json:"url"`
	Kind        int       `json:"kind"`
	PublishedAt time.Time `json:"publishedAt"`
}

type Mutation struct {
}

type ProjectInput struct {
	ID          string  `json:"id"`
	Title       string  `json:"title"`
	Description string  `json:"description"`
	IsFavorite  bool    `json:"isFavorite"`
	Position    int     `json:"position"`
	GithubLink  *string `json:"githubLink,omitempty"`
	QiitaLink   *string `json:"qiitaLink,omitempty"`
	AppLink     *string `json:"appLink,omitempty"`
}

type ProjectPosition struct {
	ID       string `json:"id"`
	Position int    `json:"position"`
}

type Query struct {
}

type TechStackInput struct {
	TechnologyID uint `json:"technologyId"`
	Proficiency  int  `json:"proficiency"`
}

type TechnologyInput struct {
	Name     string  `json:"name"`
	LogoURL  *string `json:"logoUrl,omitempty"`
	TagColor string  `json:"tagColor"`
}
