name: Build Admin for Staging
on:
  push:
    branches:
      - main
    paths:
      - "admin/**"
      - ".github/workflows/admin-staging.yaml"
  workflow_dispatch:

jobs:
  admin:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: piny940
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          push: true
          context: ./admin
          build-args: |
            "BACKEND_HOST=http://portfolio-backend-staging.default.svc.cluster.local:8080"
          file: ./admin/Dockerfile
          tags: |
            ghcr.io/piny940/portfolio-admin:main-${{ github.sha }}-${{ github.run_number }}

