name: Build App for Staging
on:
  push:
    branches:
      - main
    paths:
      - "app/**"
      - ".github/workflows/app-staging.yaml"
  workflow_dispatch:

jobs:
  app:
    runs-on: ubuntu-latest
    steps:
      - name: Get current datetime
        run: echo "TIMESTAMP=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV
      - name: Check out
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: piny940
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push Docker images
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ./app
          file: ./app/Dockerfile
          build-args: |
            BACKEND_HOST=https://stg-portfolio-backend.piny940.com
          tags: |
            ghcr.io/piny940/portfolio-app:main-${{ github.sha }}-${{ env.TIMESTAMP }}
