name: Build Backend for Staging
on:
  push:
    branches:
      - main
    paths:
      - "backend/**"
      - ".github/workflows/backend-staging.yaml"
  workflow_dispatch:

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Get current datetime
        run: echo "TIMESTAMP=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV
      - name: Check out
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: piny940
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push Docker images
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ./backend
          file: ./backend/Dockerfile
          tags: |
            ghcr.io/piny940/portfolio-backend:main-${{ github.sha }}-${{ env.TIMESTAMP }}
