name: Build App for Release
on:
  workflow_dispatch:

jobs:
  app:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: piny940
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          push: true
          context: ./app
          file: ./app/Dockerfile
          build-args: |
            BACKEND_HOST=http://portfolio-app-backend.default.svc.cluster.local:8080
            BACKEND_TOKEN=${{ secrets.BACKEND_API_TOKEN }}
          tags: |
            ghcr.io/piny940/portfolio-app:1.0.${{ github.run_number }}
            ghcr.io/piny940/portfolio-app:latest
