name: Build for Staging
on:
  push:
    branches:
      - main

jobs:
  app:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: piny940
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          push: true
          context: ./app
          file: ./app/Dockerfile
          tags: |
            ghcr.io/piny940/portfolio-app:main-${{ github.sha }}-${{ github.run_number }}

  admin-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: piny940
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          push: true
          context: ./admin-backend
          file: ./admin-backend/Dockerfile
          tags: |
            ghcr.io/piny940/portfolio-admin-backend:main-${{ github.sha }}-${{ github.run_number }}

  admin-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: piny940
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        env:
          BACKEND_HOST: https://portfolio-admin-backend-staging.default.svc.cluster.local
        with:
          push: true
          context: ./admin-frontend
          file: ./admin-frontend/Dockerfile
          tags: |
            ghcr.io/piny940/portfolio-admin-frontend:main-${{ github.sha }}-${{ github.run_number }}
