name: Build for Staging
on:
  push:
    # branches:
    #   - main
  workflow_dispatch:

jobs:
  app:
    needs: backend
    runs-on: ubuntu-latest
    steps:
      - name: Get current datetime
        run: echo "TIMESTAMP=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV
      - name: Check out
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: piny940
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          push: true
          context: ./app
          file: ./app/Dockerfile
          build-args: |
            BACKEND_HOST=https://portfolio-backend-staging.piny940.com
            BACKEND_TOKEN=${{ secrets.BACKEND_API_TOKEN }}
          tags: |
            ghcr.io/piny940/portfolio-app:main-${{ github.sha }}-${{ env.TIMESTAMP }}

  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: piny940
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          push: true
          context: ./backend
          file: ./backend/Dockerfile
          tags: |
            ghcr.io/piny940/portfolio-backend:main-${{ github.sha }}-${{ github.run_number }}

  admin:
    needs: backend
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: piny940
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          push: true
          context: ./admin
          build-args: |
            "BACKEND_HOST=http://portfolio-backend-staging.default.svc.cluster.local:8080"
          file: ./admin/Dockerfile
          tags: |
            ghcr.io/piny940/portfolio-admin:main-${{ github.sha }}-${{ github.run_number }}

  updater:
    needs: backend
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: piny940
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          push: true
          context: ./updater
          file: ./updater/Dockerfile
          tags: |
            ghcr.io/piny940/portfolio-updater:main-${{ github.sha }}-${{ github.run_number }}
