name: Test
on: [push]

env:
  NODE_VERSION: 22.20.0
jobs:
  app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
        with:
          package_json_file: "package.json"
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "pnpm"
          cache-dependency-path: "package.json"
      - run: pnpm install
      - run: pnpm test
      - name: ESLint
        run: pnpm lint
      - name: Build Test
        run: pnpm build
