name: Test
on: [push]

env:
  NODE_VERSION: 22.20.0
jobs:
  app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
        with:
          package_json_file: "app/package.json"
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "pnpm"
          cache-dependency-path: "app/package.json"
      - run: cd app && pnpm install
      - run: cd app && pnpm test
      - name: ESLint
        run: cd app && pnpm lint
      - name: Build Test
        run: cd app && pnpm build
