name: Test
on: [push]

jobs:
  frontend:
    env:
      NODE_VERSION: 20
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION}}
      - name: cache node_modules
        id: node_modules_cache_id
        uses: actions/cache@v2
        with:
          path: |
            node_modules
          key: node-v${{ env.NODE_VERSION }}-deps-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
      - name: Yarn install
        run: yarn install
      - name: Prettier && ESLint
        run: if yarn lint |& grep -E "(error|warn)"; then exit 1; fi
      - name: Yarn test
        run: if yarn test |& grep -E "failed"; then exit 1; fi
