name: Test
on: [push]

jobs:
  app:
    env:
      NODE_VERSION: 20
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION}}
      - name: cache node_modules
        id: node_modules_cache_id
        uses: actions/cache@v2
        with:
          path: |
            node_modules
          key: app-node-v${{ env.NODE_VERSION }}-deps-${{ github.workspace }}-yarn.lock
      - name: Yarn install
        run: yarn --cwd app install --frozen-lockfile
      - name: Yarn Test
        run: yarn --cwd app test
      - name: Prettier && ESLint
        run: if yarn --cwd app lint |& grep -E "(error|warn)"; then exit 1; fi
      - name: Build Test
        run: yarn --cwd app build

  backend:
    env:
      GO_VERSION: 1.21.x
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Install dependencies
        run: cd backend && go get .
      - name: Build
        run: cd backend && go build -v ./...
      - name: Test with the Go CLI
        run: cd backend && go test ./...

  updater:
    env:
      NODE_VERSION: 20
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION}}
      - name: cache node_modules
        id: node_modules_cache_id
        uses: actions/cache@v2
        with:
          path: |
            node_modules
          key: updater-node-v${{ env.NODE_VERSION }}-deps-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
      - name: Yarn install
        run: yarn --cwd updater install
      - name: Prettier && ESLint
        run: if yarn --cwd updater lint |& grep -E "(error|warn)"; then exit 1; fi
      - name: Yarn Build
        run: yarn --cwd updater build
      # - name: Yarn test
      #   run: if yarn --cwd updater test |& grep -E "failed"; then exit 1; fi
