name: Test
on: [push]

jobs:
  app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4
        with:
          package_json_file: "package.json"
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          node-version-file: "package.json"
          cache: "pnpm"
          cache-dependency-path: "pnpm-lock.yaml"
      - run: pnpm install
      - run: pnpm test
      - name: ESLint
        run: pnpm lint
      - name: Build Test
        run: pnpm build
