name: Build App to Update Data
on:
  workflow_dispatch:
  schedule:
    - cron: "15 18 * * *"

jobs:
  production:
    runs-on: ubuntu-latest
    steps:
      - name: Get current datetime
        run: echo "TIMESTAMP=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV
      - name: Check out
        uses: actions/checkout@v4
        with:
          ref: release-app
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: piny940
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          push: true
          context: ./app
          file: ./app/Dockerfile
          build-args: |
            BACKEND_HOST=https://portfolio-backend.piny940.com
            BACKEND_TOKEN=${{ secrets.BACKEND_API_TOKEN }}
          tags: |
            ghcr.io/piny940/portfolio-app:1.0.0-${{ env.TIMESTAMP }}
            ghcr.io/piny940/portfolio-app:latest
  staging:
    runs-on: ubuntu-latest
    steps:
      - name: Get current datetime
        run: echo "TIMESTAMP=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV
      - name: Check out
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: piny940
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          push: true
          context: ./app
          file: ./app/Dockerfile
          build-args: |
            BACKEND_HOST=https://portfolio-backend-staging.piny940.com
            BACKEND_TOKEN=${{ secrets.BACKEND_API_TOKEN }}
          tags: |
            ghcr.io/piny940/portfolio-app:main-${{ github.sha }}-${{ env.TIMESTAMP }}
